name: testes

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  banco-de-questoes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Conferir o banco de questões
        run: node testes/testar.js
